import { Container, Text, Button, Card, SegmentedControl, Image, createStyles} from '@mantine/core'
import Head from 'next/head'
import HeaderAction from '../components/header'
import purpleSlider from '../../public/landing-page-purple-slider.svg'
import {useState} from 'react'


// const styles = createStyles((theme) => ({
//   root: {
// 	display: 'flex',
// 	flexDirection: 'column',
// 	alignItems: 'center',
// 	justifyContent: 'center',
// 	height: '700px',
// 	width: '100vw',
// 	  },

// }))

export default function Home() {

  const [selectedHowItWorks, setSelectedHowItWorks] = useState(0)

  const testData = [
	  {
			"link": "/about",
			"label": "Features"
		},
		{
			"link": "#1",
			"label": "Learn",
			"links": [{
					"link": "/docs",
					"label": "Documentation"
				},
				{
					"link": "/resources",
					"label": "Resources"
				},
				{
					"link": "/community",
					"label": "Community"
				},
				{
					"link": "/blog",
					"label": "Blog"
				}
			]
		},
		{
			"link": "/about",
			"label": "About"
		},
		{
			"link": "/pricing",
			"label": "Pricing"
		},
		{
			"link": "#2",
			"label": "Support",
			"links": [{
					"link": "/faq",
					"label": "FAQ"
				},
				{
					"link": "/demo",
					"label": "Book a demo"
				},
				{
					"link": "/forums",
					"label": "Forums"
				}
			]
		}
	]

  return (
    <div style={{width: '100vw', height: '100vh'}}>
      <Head>
        <title>Tandem</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderAction links={testData} />
	  <div style={{
		  display: 'flex',
		  flexDirection: 'column',
		  alignItems: 'center',
		  justifyContent: 'center',
		  height: '700px',
		  width: '100vw',
		
	  }}>
			<Text sx={{
				fontSize: '96px',
				fontWeight: 700,
				lineHeight: '129px',
				width: '610px',
				textAlign: 'center',
			}}>Integrate in tandem</Text>
			<div style={{
				height: '20px'
			}}
			/>
			<Text
				sx={{
					fontSize: '22px',
					fontWeight: 100,
					lineHeight: '32px',
					width: '610px',
					textAlign: 'center',
					fontFamily: 'Visuelt',
					color: '#3E3E3E'
				}}

			>
				Turn your partnership API documentation into a simple, powerful, no-code workspace.
			</Text>
			<div style={{
				height: '40px'
			}}
			/>
			<Button
				sx={{
					width: '221px', 
					height: '76px',
					fontFamily: 'Visuelt',
					fontSize: '24px',
					fontWeight: 400,
					backgroundColor: 'black',
					color: 'white',
					'&:hover': {
						backgroundColor: '#3E3E3E',
						color: 'white',
					},

				}}
				radius="lg"
			>
				Get Started
			</Button>
	  </div>
	  <div style={{
		  display: 'flex',
		  flexDirection: 'column',
		  alignItems: 'center',
		  justifyContent: 'center',
		  height: '476px',
		  backgroundColor: '#F5F5F5',
	  }}>
		<div style={{height: '69px', width: '256px'}} >
			<Image src={purpleSlider} />
		</div>
		<div style={{height: '20px'}} />
		  <Text	
			sx={{
				fontSize: '48px',
				fontWeight: 700,
				lineHeight: '64px',
				width: '700px',
				textAlign: 'center',
			}}
			>
			Move fast and launch things
		</Text>
		<div style={{height: '20px'}} />
		<Text
		sx={{
			fontSize: '22px',
			fontWeight: 400,
			width: '700px',
			fontFamily: 'Visuelt',
			textAlign: 'center',
		}}>
			Tandem unblocks teams working on software partnerships between organizations.  PMs, engineers, and account managers can scope and launch integrations with speed, clarity, and efficiency.
		</Text>
	  </div>
	  <div style={{ padding: 100, height: '721px', display:'flex', flexDirection: 'column', width: '100vw'}}>
		<div style={{ }}>
				<Text sx={{
						fontSize: '48px',
						fontWeight: 700,
						lineHeight: '64px',
						textAlign: 'left',
					}}>
					How it works
				</Text>
		</div>
		<div style={{
			display: 'flex',
			flexDirection: 'row',
			alignItems: 'center',
			justifyContent: 'center',
			backgroundColor: 'white',
		}}>
			
			<div style={{
				display: 'flex',
				flexDirection: 'column',
				
				width: '50%',
			}}>
				
				<div style={{width: '100%', height: '100%'}}>
					<SegmentedControl 
					size={'xl'} 
					orientation="vertical" 
					classNames={{control: 'control', controlActive: 'controlActive'}}
					styles={{
						label: {
							fontSize: '24px',
							fontWeight: 400,
							lineHeight: '32px',
							color: '#000000',
							fontFamily: 'Visuelt',
							alignContent:'start',
							justifyContent: 'flex-start',
						},
						root: {
							backgroundColor: 'white',
							width: '100%'
						},
						control: {
							backgroundColor: 'white',
							padding: 20,
							'&:hover': {
								backgroundColor: '#D9FAC0',
								color: '#3E3E3E',
							},
						},
						controlActive: {
							backgroundColor: '#D9FAC0',
							color: '#3E3E3E',
							border: '2px solid black'
						}
						
					}}
					data={[
						{
							label: 'Powered by your documentation',
							value: '1',
						},
						{
							label: 'Easy data translation and mapping',
							value: '2',
						},
						{
							label: 'Manage team permissions',
							value: '3',
						},
						{
							label: 'Completely configurable',
							value: '4',
						},
						{
							label: 'Generate awesome documentation',
							value: '5',
						}
					]}
					>

					</SegmentedControl>
				
				</div>
				
				
			</div>
			<div style={{
				display: 'flex',
				flexDirection: 'column',
				alignItems: 'center',
				justifyContent: 'center',
				width: '50%',
			}}>
					<Card radius={'lg'} sx={{
						border: '1px solid #000000',
						height: '260px'
						}}>
						<Card.Section sx={{
							backgroundColor:'#D9FAC0',
							width: '400px',
							height: '40px',
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'right',

						}}>
							<Text>Test</Text>
						</Card.Section>
					</Card>
			</div>
		</div>
	  </div>
	  
    </div>
  )
}
